export const SET_FETCHED_LAYOUT = 'SET_FETCHED_LAYOUT'
export const SET_FETCHED_PART_LIST = 'SET_FETCHED_PART_LIST'
export const SET_FETCHED_PART = 'SET_FETCHED_PART'
//
export const SELECT_PART = 'SELECT_PART'
export const DESELECT_PART = 'DESELECT_PART'
